### ISSUE TITLE
After upgrade from 25.0.6 to 26.2.0 I got error cannot find module keycloak-js

### ISSUE THREAD

**Issue by konrazem** [keycloak/keycloak-js#164]
### Describe the bug

After upgrade from 25.0.6 to 26.2.0 I got error cannot find module keycloak-js.
Eslint is rasing error 
"Unable to resolve path to module 'keycloak-js'"
My tsconfig is 
```json
{
  "exclude": ["node_modules"],
  "files": ["./typings.d.ts"],
  "compilerOptions": {
    "jsx": "react",

    "skipLibCheck": true,
    "target": "ES2017",
    "useDefineForClassFields": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
  
    "preserveConstEnums": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "es2022",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,

    "noEmit": true,
    "baseUrl": "src"
  },
  "watchOptions": {
    "excludeDirectories": ["**/node_modules", "_build", "temp/*"]
  },
  "include": ["src"],
  "rules": {
    "no-empty": false
  },
  "jsRules": {
    "no-empty": true
  }
}

```
  

### Version

26.2.0

### Expected behavior

Before upgrade from 25.0.6 there was no such issue

### How to Reproduce?

Install 26.2.0 in ts react app

**Comment by jonkoops** [comment]
This must be something about the way your project is set up, likely you are using an outdated version of ESLint, or other related tooling. Try making sure all your other dependencies are up-to-date first.
